#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf postProcessing-* yplus*
rm -f *.csv *.pdf constant/turbulenceProperties

#------------------------------------------------------------------------------
